apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dns-sync.fullname" . }}
  labels:
    {{- include "dns-sync.labels" . | nindent 4 }}
data:
  config.toml: |{{ .Values.dnsSync.config | nindent 4 }}
