{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ include "dns-sync.fullname" . }}
  labels:
    {{- include "dns-sync.labels" . | nindent 4 }}
rules:

- apiGroups: [""]
  resources: ["services","pods","nodes"]
  verbs: ["get","watch","list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]

- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints"]
  verbs: ["get","watch","list"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints/status"]
  verbs: ["*"]

- apiGroups: ["acme.cert-manager.io"]
  resources: ["challenges"]
  verbs: ["get","watch","list"]
- apiGroups: ["acme.cert-manager.io"]
  resources: ["challenges/status"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ include "dns-sync.fullname" . }}
  labels:
    {{- include "dns-sync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ include "dns-sync.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dns-sync.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

{{- end }}
