name: Helm

on:
  workflow_dispatch:
  push:
    branches: [ main, helm-on-ghcr ]
    tags: [ v* ]
    paths-ignore:
      - 'manifests/**'
      - 'configs/**'
      - '*.md'
  pull_request: {}

permissions:
  contents: read

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check Helm chart

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test Chart
      run: time helm template helm-chart

  push:
    needs: check
    runs-on: ubuntu-latest
    name: 'Push Helm chart'
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine image tag
        id: name
        run: |
          IMAGE_ID=ghcr.io/cloudydeno/dns-sync
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]
          then VERSION=$( echo $VERSION | sed -e 's/^v//' )
          else VERSION=$( echo ${{ github.sha }} | cut -c1-7 )
          fi
          echo "Will push to $IMAGE_ID:$VERSION"
          echo "image=$IMAGE_ID" >> $GITHUB_OUTPUT
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        run: echo "${GITHUB_TOKEN}" | helm registry login ghcr.io --username ${GITHUB_ACTOR} --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package chart
        working-directory: helm-chart
        run: helm package . -u -d dist --app-version "${{ steps.name.outputs.tag }}"

      - name: Push chart
        working-directory: helm-chart
        run: helm push dist/*.tgz oci://ghcr.io/cloudydeno/charts
